name: C CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: cat /proc/stat
    - run: cat /proc/diskstats
    - run: cat /proc/self/mountstats
    - run: cat /proc/meminfo

    - name: Compile and Run for Half a Minute
      run: make -f ./Makefile ARGS="-t 30000"

    - name: Compile and Run for 15 Minutes
      run: make -f ./Makefile ARGS="-t 900000"

    - name: Upload The Artifact
      uses: actions/upload-artifact@v1
      with:
          name: resource_usage_tracker
          path: ./build/resource_usage_tracker

