name: C CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: cat /proc/stat
    - run: cat /proc/diskstats
    - run: cat /proc/self/mountstats
    - run: cat /proc/meminfo

    - name: Compile and Run
      run: make -f ./Makefile

